### ISSUE TITLE
ModuleNotFoundError: No module named 'data.dataset.multiwoz'

### ISSUE THREAD

**Issue by nowyouseemejoe** [YuxiaWu/SimpleDyG#1]
It complaints  `ModuleNotFoundError: No module named 'data.dataset.multiwoz'` error when I tried `bash train_UCI_13.sh`. Is there a missing file `multiwoz.py`?

**Comment by YuxiaWu** [comment]
Hi, @nowyouseemejoe Thank you for your interest.  Sorry for the confusion. Accurately we don't need the multiwoz.py. I have fixed it by deleting the related code in 'data/ __init__.py' and 'data/dataset/__init__.py'

**Comment by nowyouseemejoe** [comment]
Hi @YuxiaWu 
It works now. Thank you for your quick response :)
