### ISSUE TITLE
A Quesion about Dataset Segmentation

### ISSUE THREAD

**Issue by SwaggyZhang** [YuxiaWu/SimpleDyG#3]
Hello, thank you for your excellent work!

I find that the files in `\resource\` are generated with the `ml_${dataname}.csv` file.

However, the `ml_${dataname}.csv` file is generated by the `data_trans.py` with the `train_data` in  `line 44`.

For instance,  the maximum node index in  `ml_uci.csv` file is 1780, while the maximum node index in the UCI dataset is greater than 1800.

The `val_test_data` in `data_trans.py` is not used for validating or testing.

Thus, the model will not deal with the out-of-vocabulary tokens, i.e., new nodes.

I wonder that how does the model deal with the new nodes during test phase.

Looking forward to your reply~

**Comment by YuxiaWu** [comment]
Hi, Thank you for your interest in our work. That's a great question. In our paper, we use the Hepth citation dataset, which does include out-of-vocabulary (OOV) tokens during the testing phase. We address this by using text features from the abstracts of each node as initial node features, allowing us to handle OOV tokens effectively. However, if the dataset lacks additional side information, our model would not be able to manage the OOV scenario.

**Comment by SwaggyZhang** [comment]
Thank you for your reply! 

By the way, is it convenient for you to release the hyper-parameter of different datasets?

**Comment by YuxiaWu** [comment]
@SwaggyZhang Hi, I have uploaded the hyper-parameter of other datasets in train_seed_[dataname].sh

**Comment by SwaggyZhang** [comment]
Wow~ Thank you for your generous help!

As for the baselines, it would be great if you could please release any code for them!

Hope you have more exciting research!
