### ISSUE TITLE
Where is the code for time step alignment?

### ISSUE THREAD

**Issue by Tianyu9748** [YuxiaWu/SimpleDyG#6]
Hi, 
I cannot find the part of the codes for the time step alignment.
Could you tell me the file containing the function for the time stap alignment?

Best
Tianyu

**Comment by YuxiaWu** [comment]
@Tianyu9748 Hi, Tianyu. The time step alignment process involves adding temporal special tokens into the sequence such as the <|time0|>, <|time1|>... You can find the process in csv2resources.py.
