### ISSUE TITLE
The args of the timestamp setting

### ISSUE THREAD

**Issue by ZeroerWiser** [YuxiaWu/SimpleDyG#7]
Congratulation to this great work! But I don't understand the setting of timestampes in the such 'sh' file, and it triggered the error.

**Comment by YuxiaWu** [comment]
@ZeroerWiser  Thanks for your interest. The timestamp in `sh` file is an indicator of the timestamp of testing data. I don't know what kind of error you encountered. You can change it: for example, in UCI dataset, you can set it timetamp=12. Just remember to refine the corresponding folder name of the dataset if you change it to another number.
